export const services = [
  {
    id: 1,
    providerName: "Valentina Ruiz",
    providerImg: "https://cdn-icons-png.flaticon.com/512/847/847969.png",
    category: "Belleza y Bienestar",
    subcategory: "Masajes relajantes",
    date: "24/11/2025",
    time: "15:00",
    duration: "1 hora",
    address: "España, Buenos Aires",
    paymentMethod: "Tarjeta de crédito",
    servicePrice: 15000,
    fee: 2000,
    rating: 4.5,
    reviewsCount: 12,
  },
  {
    id: 2,
    providerName: "Diego Fernández",
    providerImg: "https://cdn-icons-png.flaticon.com/512/847/847969.png",
    category: "Estética",
    subcategory: "Corte de cabello",
    date: "25/11/2025",
    time: "10:30",
    duration: "45 min",
    address: "Av. Siempre Viva 456, Buenos Aires",
    paymentMethod: "Efectivo",
    servicePrice: 1200,
    fee: 150,
    rating: 5,
    reviewsCount: 8,
  }
];